apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: opsdesk
  namespace: argocd
  labels:
    app.kubernetes.io/name: opsdesk
    app.kubernetes.io/part-of: opsdesk-devsecops-platform
spec:
  description: OpsDesk DevSecOps Platform GitOps project

  sourceRepos:
    - https://github.com/poiboiq/opsdesk-devsecops-platform.git

  destinations:
    - namespace: opsdesk
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: storage.k8s.io
      kind: StorageClass

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
