apiVersion: v1
kind: Secret
metadata:
  name: opsdesk-secrets
  namespace: opsdesk
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: opsdesk-admin
  MONGO_INITDB_ROOT_PASSWORD: opsdesk-password
  MONGO_URI: mongodb://opsdesk-admin:opsdesk-password@mongodb:27017/opsdesk?authSource=admin
